#!/bin/bash

# Base Script File (%PLACE_FILENAME%)
# Created: %PLACE_CREATETIME%
# Version: 1.0
# Author: Author <email@gmail.com>
#
# This Bash script was developped by Author.
# You are free to copy, adapt or modify it.

%PLACE_CURSOR%
