#!/usr/bin/python2
# coding=utf-8

# Base Python 2 File (%PLACE_FILENAME%)
# Created: %PLACE_CREATETIME%
# Version: 1.0
#
# This Python 2 script was developped by Author.
# You are free to copy, adapt or modify it.
#
# (ɔ) Author <email@gmail.com>

%PLACE_CURSOR%
